services:
  CryptoAlertItaliaBot:
    image: oven/bun:1
    container_name: CryptoAlertItaliaBot
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
    expose:
      - "3000"
    command: ["sh", "-c", "bun install && bunx prisma generate && bunx prisma db push && bun run start"]
    restart: unless-stopped
#     networks:
#       - proxy-manager

# networks:
#   proxy-manager:
#     external: true
